### ISSUE TITLE
twitter.rb プラグインを利用すると REXML::ParseException が発生する

### ISSUE THREAD

**Issue by bynnchapu** [tdiary/tdiary-contrib#221]
**Describe the bug / 不具合の説明**
twitter.rb を有効な状態にしたところ、 `REXML::ParseException` が発生します。

**To Reproduce / 再現手順**
update.rb?conf=sp にて、 `twitter.rb` を有効にします。

**Expected behavior / 期待した動作**
自身の tDiary サイトが表示される。

**Screenshots / スクリーンショット**
![image](https://user-images.githubusercontent.com/1008151/83959403-772ada00-a8b7-11ea-93bc-2cb1c2575bb4.png)

スタックトレースは以下のとおりです。
```
REXML::ParseException
Missing attribute equal: <data-rdm>
Line: 72
Position: 7136
Last 80 unconsumed characters:
/usr/local/lib/ruby/2.7.0/rexml/parsers/baseparser.rb:519:in `block in parse_attributes'
/usr/local/lib/ruby/2.7.0/rexml/parsers/baseparser.rb:510:in `loop'
/usr/local/lib/ruby/2.7.0/rexml/parsers/baseparser.rb:510:in `parse_attributes'
/usr/local/lib/ruby/2.7.0/rexml/parsers/baseparser.rb:378:in `pull_event'
/usr/local/lib/ruby/2.7.0/rexml/parsers/baseparser.rb:183:in `pull'
/usr/local/lib/ruby/2.7.0/rexml/parsers/treeparser.rb:23:in `parse'
/usr/local/lib/ruby/2.7.0/rexml/document.rb:288:in `build'
/usr/local/lib/ruby/2.7.0/rexml/document.rb:45:in `initialize'
(plugin/twitter.rb):21:in `new'
(plugin/twitter.rb):21:in `block (2 levels) in load_plugin'
/usr/src/app/lib/tdiary/plugin.rb:114:in `block in header_proc'
/usr/src/app/lib/tdiary/plugin.rb:113:in `each'
/usr/src/app/lib/tdiary/plugin.rb:113:in `header_proc'
(TDiary::Plugin#eval_src):5:in `eval_src'
/usr/src/app/lib/tdiary/plugin.rb:95:in `eval'
/usr/src/app/lib/tdiary/plugin.rb:95:in `eval_src'
/usr/src/app/lib/tdiary/base.rb:65:in `do_eval_rhtml'
/usr/src/app/lib/tdiary/base.rb:29:in `eval_rhtml'
/usr/src/app/lib/tdiary/dispatcher/index_main.rb:37:in `run'
/usr/src/app/lib/tdiary/dispatcher/index_main.rb:5:in `run'
/usr/src/app/lib/tdiary/dispatcher.rb:25:in `dispatch_cgi'
/usr/src/app/lib/tdiary/dispatcher.rb:20:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:74:in `block in call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `call'
/usr/src/app/lib/tdiary/rack/valid_request_path.rb:15:in `block in call'
/usr/src/app/lib/tdiary/rack/valid_request_path.rb:14:in `each'
/usr/src/app/lib/tdiary/rack/valid_request_path.rb:14:in `call'
/usr/src/app/lib/tdiary/rack/static.rb:20:in `call'
/usr/src/app/lib/tdiary/rack/html_anchor.rb:19:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:74:in `block in call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:74:in `block in call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `call'
/usr/src/app/lib/tdiary/application.rb:52:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/reloader.rb:49:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/lint.rb:50:in `_call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/lint.rb:38:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/show_exceptions.rb:23:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/common_logger.rb:38:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/content_length.rb:17:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Environment / 動作環境**
Docker イメージ版の tdiary を利用しています。
 - ホストOS: CentOS7.8.2003
    - Docker version: Docker version 1.13.1, build 64e9980/1.13.1
        - CentOS rpm version: docker-1.13.1-161.git64e9980.el7_8.x86_64
 - Browser: Google Chrome 83.0.4103.61 for Windows
- tDiary Docker image: tdiary/tdiary:latest `2a1f11a2cc62bfd4e903fc63d0cc9d6f80de199224cc05e091af8c2c89dee0e7`
    - 切り分けのために、最新のイメージを利用してみましたが、同様でした。
 - tDiary Version:  tDiary version 5.1.2
    - Ruby Version: Powered by Ruby version 2.7.1-p83

**Comment by satoryu** [comment]
https://github.com/tdiary/tdiary-contrib/blob/a3b8c6b611ef3f66b47f88918d73ddf1681dbecd/plugin/twitter.rb#L17

試しにこのURLをcurlで叩いてみると、httpsにリダイレクトされるようになっていますね。

```sh
$ curl -v 'http://twitter.com/statuses/user_timeline/sato_ryu.xml' 
*   Trying 104.244.42.193:80...
* TCP_NODELAY set
* Connected to twitter.com (104.244.42.193) port 80 (#0)
> GET /statuses/user_timeline/sato_ryu.xml HTTP/1.1
> Host: twitter.com
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< content-length: 0
< date: Sat, 20 Jun 2020 14:28:33 GMT
< location: https://twitter.com/statuses/user_timeline/sato_ryu.xml
< server: tsa_m
< set-cookie: personalization_id="v1_GaZEfwMt1zw3QB+QXXekIw=="; Max-Age=63072000; Expires=Mon, 20 Jun 2022 14:28:33 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
< set-cookie: guest_id=v1%3A159266331375349762; Max-Age=63072000; Expires=Mon, 20 Jun 2022 14:28:33 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
< x-connection-hash: 81bc04b72d686ae8217e0207eea807d0
< x-response-time: 100
< 
* Connection #0 to host twitter.com left intact
```

ということで、該当箇所で`open`しているURLのスキーマを変えれば直りそうなので、試してみます。

**Comment by satoryu** [comment]
## 原因調査

例外処理の実装を見ると、xml要素の属性は「名前=値」というペアであることが仕様で決まっている。
- https://github.com/ruby/rexml/blob/be62163ba12a6657679a34e472b1d29d75e0e881/lib/rexml/parsers/baseparser.rb#L517-L520
- [Extensible Markup Language (XML) 1.0 (Fifth Edition)](https://www.w3.org/TR/xml/#sec-starttags)

例外が指すように、レスポンスのXML中72行目に値を持たない属性があるため、この例外が発生している。

```xml
  <link rel="canonical" href="https://twitter.com/statuses/user_timeline/sato_ryu.xml" data-rdm />
```

**Comment by satoryu** [comment]
レスポンスがXMLではなく、HTMLだということがわかりました。まだソースは見つけられていませんが、タイムラインのこの取得方法はもう仕様できないのかもしれません。

参考のため、`https://twitter.com/statuses/user_timeline/sato_ryu.xml` のレスポンスを添付します。
[sato_ryu.xml](https://github.com/tdiary/tdiary-contrib/files/4808185/sato_ryu.txt)

**Comment by tdtds** [comment]
htmlとして開くと「Sorry, that page doesn’t exist!」と出ますね。実際Twitterは、正規のAPIを経由しない機械アクセスはとっくに禁止している状況だったと認識してます。このプラグインは寿命ですかね?

**Comment by satoryu** [comment]
このプラグインを自分は使ったこと無いのですが、tDiaryとしては必要ないように思いました。
やりたいことはTwitterが公式に提供しているタイムラインの埋め込みのように見えました。
- [Overview — Twitter Developers](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview)

tDiaryの設定から、ヘッダ・フッタの変更ができるので、そこに埋め込みのHTMLタグを追加することで同様のことができると思います。

**Comment by tdtds** [comment]
厳密には同様ではない（このプラグインは日々の日記にその日の発言を追加するもの）ですが、同様の機能を今の仕様のままで実現するのは、Twitterの制限的にムリですね。日記上では何も表示しないようにして、プレビュー時にのみメッセージを出す方向でお蔵入りにしましょう。
